baseURL: https://asyncplus.codes
languageCode: en-us
title: Async+ ⛓
theme: fresh
googleAnalytics: UA-221751024-1
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/text-logo.svg
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Chainable async/await in Swift
    # Hero subtitle (optional)
    subtitle: "A simple chainable interface for your async and throwing code, similar to promises and futures."
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "https://docs.asyncplus.codes/getting-started/"
    # Hero image (from static/images/___)
    image: shot-sketch.png
    # Footer logos (from static/images/logos/clients/___.svg)
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Home
    url: /
  - title: Docs
    url: https://docs.asyncplus.codes/
  - title: GitHub
    url: https://github.com/async-plus/async-plus/
  - title: Chat
    url: https://discord.gg/vaAhGvvHpW
  footer:
    # Logo (from /images/logos/___)
    logo: text-logo.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/async-plus
      icon: github
    - link: https://twitter.com/async_plus
      icon: twitter
    quicklinks:
      column1:
        title: "Community"
        links:
        - text: Discord
          link: https://discord.gg/vaAhGvvHpW
        - text: GitHub
          link: https://github.com/async-plus/async-plus
      column2:
        title: "Docs"
        links:
        - text: Index
          link: https://docs.asyncplus.codes/
        - text: Getting Started
          link: https://docs.asyncplus.codes/getting-started/
        - text: Operations Reference
          link: https://docs.asyncplus.codes/operations/
